kind = "mobile"
previewPath = "/freshcart-mobile/"
title = "FreshCart Mobile"
version = "1.0.0"
id = "artifacts/freshcart-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/freshcart-mobile/" ]
localPort = 22070

[services.development]
run = "pnpm --filter @workspace/freshcart-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/freshcart-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/freshcart-mobile", "run", "serve" ]

[services.env]
PORT = "22070"
BASE_PATH = "/freshcart-mobile/"
